/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Katsuo
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        getContentPane().setBackground(new Color(27, 89, 7)); // cambia el color de fondo
        generadorNum = new NumeroAleatorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ingresoTxt = new java.awt.TextField();
        minRange = new java.awt.TextField();
        maxRange = new java.awt.TextField();
        enterNum = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        resultadoTxt = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 102));

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setForeground(new java.awt.Color(0, 51, 0));

        ingresoTxt.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        ingresoTxt.setText("Ingresar numero");
        ingresoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoTxtMouseClicked(evt);
            }
        });
        ingresoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoTxtActionPerformed(evt);
            }
        });
        ingresoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoTxtKeyTyped(evt);
            }
        });

        minRange.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        minRange.setText("1");
        minRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minRangeActionPerformed(evt);
            }
        });
        minRange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                minRangeKeyTyped(evt);
            }
        });

        maxRange.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        maxRange.setText("10");
        maxRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxRangeActionPerformed(evt);
            }
        });
        maxRange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maxRangeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(minRange, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ingresoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(maxRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingresoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        enterNum.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enterNum.setLabel("Probar num");
        enterNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                enterNumMouseReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 102, 0));
        jPanel3.setForeground(new java.awt.Color(0, 51, 0));

        resultadoTxt.setEditable(false);
        resultadoTxt.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        resultadoTxt.setText("     Resultado");
        resultadoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultadoTxtMouseClicked(evt);
            }
        });
        resultadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoTxtActionPerformed(evt);
            }
        });
        resultadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                resultadoTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(enterNum, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(enterNum, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterNumMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterNumMouseReleased
        int minRangeInt = Integer.parseInt(minRange.getText());
        int maxRangeInt = Integer.parseInt(maxRange.getText());
        generadorNum.setMinRange(minRangeInt);
        generadorNum.setMaxRange(maxRangeInt);
        int jml = Integer.parseInt(ingresoTxt.getText());
        definirResultado(generadorNum.verificarNumeros(jml));
        System.out.println(generadorNum.getNumeroAleatorio());
        ingresoTxt.setText(ORIGINAL_TEXT);

    }//GEN-LAST:event_enterNumMouseReleased

    private void definirResultado(boolean resultado) {
        if (resultado) {
            resultadoTxt.setText(RESULTADO_TRUE);
            mostrarImagen();
        } else {
            resultadoTxt.setText(RESULTADO_FALSE);
        }
    }

    private void mostrarImagen() {
        try {
            BufferedImage img = ImageIO.read(new File("1.jpg"));//ver que funcion cumple, no es necesario esta linea
            ImageIcon icon = new ImageIcon("1.jpg");
            JLabel label = new JLabel(icon);
            JOptionPane.showMessageDialog(null, label);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    private void ingresoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoTxtKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_ingresoTxtKeyTyped

    private void ingresoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoTxtActionPerformed

    private void ingresoTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoTxtMouseClicked
        ingresoTxt.setText(DEF_TEXT);
    }//GEN-LAST:event_ingresoTxtMouseClicked

    private void resultadoTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultadoTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoTxtMouseClicked

    private void resultadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoTxtActionPerformed

    private void resultadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultadoTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoTxtKeyTyped

    private void minRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minRangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minRangeActionPerformed

    private void maxRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxRangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxRangeActionPerformed

    private void minRangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minRangeKeyTyped
        System.out.println(minRange.getText());
        char enter = evt.getKeyChar();
        verificarTxtVacio(evt);
        if ((!(Character.isDigit(enter))) || (minRange.getText().length() > MAX_MIN_RANGE_TXT)) {
            evt.consume();
        }
        System.out.println(minRange.getText());
    }//GEN-LAST:event_minRangeKeyTyped

    private void verificarTxtVacio(java.awt.event.KeyEvent evt) {
        int minRangeInt;
        int maxRangeInt;
        if ((minRange.getText().length() != 0) && (maxRange.getText().length() != 0)) {
            minRangeInt = Integer.parseInt(minRange.getText());
            maxRangeInt = Integer.parseInt(maxRange.getText());
        } else {
            minRangeInt = 0;
            maxRangeInt = 0;
        }
        if (minRangeInt > maxRangeInt) {
            evt.consume();
            maxRange.setBackground(Color.RED);
        } else {
            maxRange.setBackground(Color.WHITE);
        }
    }

    private void maxRangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maxRangeKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        } else if (maxRange.getText().length() > MAX_MIN_RANGE_TXT) {
            evt.consume();
        }
    }//GEN-LAST:event_maxRangeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    //Variables-Constantes definidas por el "usuario"
    NumeroAleatorio generadorNum = null;
    private static final String DEF_TEXT = "";
    private static final String ORIGINAL_TEXT = "Ingresar numero";

    private static final String RESULTADO_TRUE = "ACERTO :3";
    private static final String RESULTADO_FALSE = "NO ACERTO :(";

    private static final int INDEX_INICIAL = 0;
    private static final int MAX_MIN_RANGE_TXT = 1;
    private static final int CARET_DEF_POS = 2;

    //private String textoSalida = DEF_TEXT;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button enterNum;
    private java.awt.TextField ingresoTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private java.awt.TextField maxRange;
    private java.awt.TextField minRange;
    private java.awt.TextField resultadoTxt;
    // End of variables declaration//GEN-END:variables

    /**
     * *********************************
     *
     *
     * TIPS DE LAS VARIABLES DECLARADAS ARRIBA * - Cuando se cambia el nombre
     * mediante el diseño automaticamente se cambia el nombre en el codigo -
     *
     **********************************
     */
}
